version: "3.5"
services:
    nginx:
      image: nginx:1.17.9-alpine
      env_file:
        - .env
      ports:
        - "80:80"
      volumes:
        - .:/src
        - asset-volume:/home
        - ./config:/etc/nginx/conf.d
      deploy:
        restart_policy:
          max_attempts: 3
          condition: on-failure
        replicas: 1
        placement:
          constraints: [node.role == manager]
      networks: 
        - main_front_network
      depends_on:
        - web
    web:
      env_file:
        - .env
      build: .
      image: front_image:latest
      deploy:
        update_config:
          parallelism: 1
          max_failure_ratio: 0
          delay: 3s
          failure_action: rollback
        restart_policy:
          max_attempts: 3
          condition: on-failure
        replicas: 5
        placement:
          constraints: [node.role == manager]
  
      volumes:
        - asset-volume:/home
        - .:/src
      networks: 
        - main_front_network
networks: 
  main_front_network:
      driver: overlay
volumes:
    asset-volume:
    